/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.itson.mango.ui;

import mx.itson.mango.entidades.Computadora;
import mx.itson.mango.entidades.Television;

/**
 *
 * @author alumnog
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        lblComputadora = new javax.swing.JLabel();
        lblTv = new javax.swing.JLabel();
        lblCMarca = new javax.swing.JLabel();
        lblCModelo = new javax.swing.JLabel();
        libCdirecionIP = new javax.swing.JLabel();
        lblMemoriaRAM = new javax.swing.JLabel();
        lblMemoriaDisco = new javax.swing.JLabel();
        txtmarcaComp = new javax.swing.JTextField();
        txtModeloComp = new javax.swing.JTextField();
        txtIPComp = new javax.swing.JTextField();
        txtRAMComp = new javax.swing.JTextField();
        txtMemoriaDDComp = new javax.swing.JTextField();
        lblVolumen = new javax.swing.JLabel();
        txtMarcaTV = new javax.swing.JTextField();
        txtModeloTV = new javax.swing.JTextField();
        txtIPTV = new javax.swing.JTextField();
        txtPulgadas = new javax.swing.JTextField();
        txtVolumenActual = new javax.swing.JTextField();
        lblTMarca = new javax.swing.JLabel();
        lblTModelo = new javax.swing.JLabel();
        lblTDirecionIP = new javax.swing.JLabel();
        lblPulgadas = new javax.swing.JLabel();
        setAtributos = new javax.swing.JButton();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblComputadora.setText("Computadora");

        lblTv.setText("Telvision");

        lblCMarca.setText("Marca");

        lblCModelo.setText("Modelo");

        libCdirecionIP.setText("Direcion IP");

        lblMemoriaRAM.setText("Memoria RAM");

        lblMemoriaDisco.setText("Memoria DD");

        txtModeloComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloCompActionPerformed(evt);
            }
        });

        txtMemoriaDDComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMemoriaDDCompActionPerformed(evt);
            }
        });

        lblVolumen.setText("Volumen Actual");

        lblTMarca.setText("Marca");

        lblTModelo.setText("Modelo");

        lblTDirecionIP.setText("Direcion IP");

        lblPulgadas.setText("Pulgadas");

        setAtributos.setText("OK");
        setAtributos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setAtributosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(lblComputadora))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCModelo)
                            .addComponent(lblCMarca)
                            .addComponent(libCdirecionIP)
                            .addComponent(lblMemoriaRAM)
                            .addComponent(lblMemoriaDisco))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmarcaComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModeloComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIPComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRAMComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMemoriaDDComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblVolumen)
                            .addComponent(lblTMarca)
                            .addComponent(lblTModelo)
                            .addComponent(lblTDirecionIP)
                            .addComponent(lblPulgadas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMarcaTV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModeloTV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIPTV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPulgadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVolumenActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTv)
                        .addGap(81, 81, 81))))
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(setAtributos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComputadora)
                    .addComponent(lblTv))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCMarca)
                            .addComponent(txtmarcaComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCModelo)
                            .addComponent(txtModeloComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(libCdirecionIP)
                            .addComponent(txtIPComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMemoriaRAM)
                            .addComponent(txtRAMComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMemoriaDisco)
                            .addComponent(txtMemoriaDDComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTMarca)
                            .addComponent(txtMarcaTV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTModelo)
                            .addComponent(txtModeloTV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTDirecionIP)
                            .addComponent(txtIPTV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPulgadas)
                            .addComponent(txtPulgadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVolumen)
                            .addComponent(txtVolumenActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(setAtributos)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtModeloCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloCompActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloCompActionPerformed

    private void txtMemoriaDDCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMemoriaDDCompActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMemoriaDDCompActionPerformed

    private void setAtributosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setAtributosActionPerformed
        String marcaComp = txtmarcaComp.toString();
        String modeloComp = txtModeloComp.toString();
        String ipComp = txtIPComp.toString();
        int RAMComp = Integer.parseInt(txtRAMComp.toString());
        int memoriaDDComp = Integer.parseInt(txtMemoriaDDComp.toString());
        Computadora comp = new Computadora( marcaComp, modeloComp, ipComp, RAMComp, memoriaDDComp);
        
        String marcaTV = txtMarcaTV.toString();
        String modeloTV = txtModeloTV.toString();
        String ipTV = txtIPTV.toString();
        int pulgadasTV = Integer.parseInt(txtPulgadas.toString());
        int volumenTV = Integer.parseInt(txtVolumenActual.toString());
        Television tv = new Television(marcaTV, modeloTV, ipTV, pulgadasTV, volumenTV);
    }//GEN-LAST:event_setAtributosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel lblCMarca;
    private javax.swing.JLabel lblCModelo;
    private javax.swing.JLabel lblComputadora;
    private javax.swing.JLabel lblMemoriaDisco;
    private javax.swing.JLabel lblMemoriaRAM;
    private javax.swing.JLabel lblPulgadas;
    private javax.swing.JLabel lblTDirecionIP;
    private javax.swing.JLabel lblTMarca;
    private javax.swing.JLabel lblTModelo;
    private javax.swing.JLabel lblTv;
    private javax.swing.JLabel lblVolumen;
    private javax.swing.JLabel libCdirecionIP;
    private javax.swing.JButton setAtributos;
    private javax.swing.JTextField txtIPComp;
    private javax.swing.JTextField txtIPTV;
    private javax.swing.JTextField txtMarcaTV;
    private javax.swing.JTextField txtMemoriaDDComp;
    private javax.swing.JTextField txtModeloComp;
    private javax.swing.JTextField txtModeloTV;
    private javax.swing.JTextField txtPulgadas;
    private javax.swing.JTextField txtRAMComp;
    private javax.swing.JTextField txtVolumenActual;
    private javax.swing.JTextField txtmarcaComp;
    // End of variables declaration//GEN-END:variables
}
